# fly.toml file for Malcolm AI Omni API
# Multi-region deployment: London, Newark, Singapore (3 shared machines)

app = "malcolm-ai"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  MALCOLM_ASYNC_MODE = "eventlet"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[deploy]
  strategy = "rolling"

[experimental]
  auto_rollback = true

[processes]
  app = ""

[vm]
  size = "shared-cpu-1x"

[scale]
  count = 3

[checks]
  [checks.health]
    type = "http"
    port = 8080          # ✅ Explicit port for health check
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"


[regions]
  lhr = 1
  ewr = 1
  sin = 1
