app = "malcolm-ai"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  MALCOLM_ASYNC_MODE = "eventlet"
  MALCOLM_SECRET = "super_secure_secret"
  MALCOLM_API_KEYS = '{"KEY_COSMIC_ALPHA":"UserAlpha","KEY_OMEGA_ROOT":"OmegaMaster"}'

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
